### ISSUE TITLE
Suggestion: inject presenter

### ISSUE THREAD

**Issue by sergiandreplace** [n1x0nj4/flutter-mvp#1]
You should probably inject the presenter instead of instantiating it.  Just a suggestion

https://github.com/n1x0nj4/flutter-mvp/blob/0c746e55a3fb87a4b56221f29386e98747c6b23c/lib/features/home/home_view.dart#L39

**Comment by n1k3c** [comment]
Yup! Waiting for real DI solution. 

ps. be free to make PR.
